### ISSUE TITLE
Jangaroo Migration to Ext AS 6 - IntelliJ IDEA Plugin won't work

### ISSUE THREAD

**Issue by dascheib** [CoreMedia/jangaroo-tools#58]
See also: [CoreMedia Support Ticket 46032](https://support.coremedia.com/hc/en-us/requests/46032)

Migration Step 7:
* Enter the version of ext-as (as in the previous step), e.g. 6.2.0-6

leads to:

* IntelliJ IDEA 2017.x.x
  * nothing happens
* IntelliJ IDEA 2016.3.x
  * errormessage: **"Required library not found: The library 'net.jangaroo:ext-as:6.2.0-6' not found in Maven repositories."**

But the library is present in the local repository - this is guaranteed after performing step 6.
The working device is a Lenovo P51 which is running on Win10.

**Comment by fwienber** [comment]
Unfortunately, the [Jangaroo IDEA Migration Plugin](https://github.com/CoreMedia/jangaroo-idea-migration/) is currently not compatible with IDEA 2017 due to incompatible API changes, and a quick fix I tried did not make it work, so please continue using latest IDEA 2016.3 for migration. After migration, IDEA plugin "Jangaroo 4" works in IDEA 2017 like a charm.

For the error occurring with IDEA 2016.3, please check
  Settings > Build, Execution, Deployment > Build Tools > Maven
On the right-hand side, you'll find "Local repository". Do to custom configuration, this may point to a different directory than the one to which you downloaded the artifact in step 6. So please make sure that below this directory, the following file exists:
  net\jangaroo\ext-as\6.2.0-6\ext-as-6.2.0-6.jar

If it doesn't (which I suppose is the case), it means that either your command line or your IDEA installation uses a custom Maven repository. Either change your command line Maven settings and repeat step 6, or adjust the "Local repository" directory in IDEA to exactly the one you use on the command line.

Hoping this helps!

**Comment by dascheib** [comment]
Thank you for your reply.
Unfortunately I couldn't fix the problem with the help of your advices.

IntelliJ IDEA, the command line - everything is using the same version of maven and so the same location for the local repository. I made a screenshot of my setup and uploaded it to the CoreMedia support ticket.

If I'm missing some hidden settings, please tell me.

Thank you!

**Comment by fwienber** [comment]
The same Maven version does not necessarily imply the same local Maven repository.
Check which one is actually used on the command line with

    mvn help:evaluate -Dexpression=settings.localRepository

**Comment by dascheib** [comment]
Both (the Windows command line and the IntelliJ IDEA Terminal) point to the configured lokal repository - "C:\work\repo". This is configured in the settings.xml file under "C:\Users\xxx\ .m2" - which is used by the version of maven, that is used by the system (Environment Variables) and IntelliJ IDEA (settings described by you in the post above).

Is there some kind of a debug mode of your plugin that is "talking" a bit more? 
Or is there a way to start the plugin over command line / Terminal with parameters?

**Comment by fwienber** [comment]
(Translated) solution from the CoreMedia support ticket:
The plugin tries to download the ext-as artifact and several others, so you have to be online, even when the primary artifact is already present in your local Maven repository.
In this case, the "offline" mode was caused by IDEA failing to auto-detect or use the Web proxy correctly, and was solved by switching off automatic proxy detection here:
Settings > Appearance & Behavior > System Settings > HTTP Proxy: Auto-detect proxy settings

Thanks, Daniel, for finding out and reporting the solution!

**Comment by fwienber** [comment]
Just added a warning of this pitfall to the [migration documentation page](https://github.com/CoreMedia/jangaroo-tools/wiki/Migrate-Jangaroo-2-to-4), step 7.
